[package]
name = "spreadsheet"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11"
eframe={version= "0.31.1", optional=true}
egui={version= "0.31.1", optional=true}

[features]
gui = ["eframe", "egui"]