edition = "2024"
style_edition = "2024"
max_width = 300
wrap_comments = true
format_code_in_doc_comments = true
imports_layout = "Vertical"
reorder_imports = true
group_imports = "StdExternalCrate"
use_small_heuristics = "Max"
error_on_line_overflow = true
struct_field_align_threshold = 20
match_arm_blocks = false
fn_params_layout = "Vertical"
where_single_line = false
control_brace_style = "AlwaysSameLine"
trailing_comma = "Vertical"
indent_style = "Block"
tab_spaces = 4
unstable_features = true
format_macro_matchers = true
format_strings = true
fn_call_width = 200
